version: "3"
services:
  api:
    container_name: fast_api
    platform: linux/x86_64
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    tty: true
    volumes:
      - ./static:/code/static
    ports:
      - 80:80
    environment:
      - HOST_URL=http://0.0.0.0:80
    env_file:
      - .env
